version: '3.12'

services:
  app:
    build: .
    volumes:
      - .:/imagereminder
    ports:
      - 8000:8000
    image: app:imagereminder
    container_name: image_reminder_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis

  celery:
    build: .
    volumes:
      - .:/imagereminder
    image: app:imagereminder
    container_name: celery_worker
    command: celery -A ImageReminder worker --loglevel=info
    depends_on:
      - redis

  celery_beat:
    build: .
    volumes:
      - .:/imagereminder
    image: app:imagereminder
    container_name: celery_beat
    command: celery -A ImageReminder beat --loglevel=info
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    container_name: redis_container
    ports:
      - "6379:6379"