# Generated by Django 5.0.7 on 2025-06-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=255)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('token_type', models.IntegerField(choices=[(0, 'Android'), (1, 'iOS'), (2, 'Web')], default=0)),
            ],
        ),
    ]
